name: "brahma"
version: 0.0.7
services:
  node1:
    hostname: node1
    entrypoint:
      - sleep
      - infinity
    build:
      context: dependency
      target: master
    init: true
    volumes:
      - shared:/mount/shared
    ports:
      - 80:80
      - 22:22
volumes:
  shared:
