
///
/// This file is generated by tools/generate_interfaces.py
/// Generated on: 2025-03-07 17:37:22
///

#ifndef BRAHMA_MPIIO_H
#define BRAHMA_MPIIO_H
#include <brahma/brahma_config.hpp>
#ifdef BRAHMA_ENABLE_MPI
#include <brahma/interceptor.h>
#include <brahma/interface/interface.h>
#include <mpi.h>

namespace brahma {
class MPIIO : public Interface {
 private:
  static std::shared_ptr<MPIIO> my_instance;

 public:
  MPIIO() : Interface(){};

  virtual ~MPIIO(){};

  static std::shared_ptr<MPIIO> get_instance();

  static int set_instance(std::shared_ptr<MPIIO> instance_i);

  template <typename C>
  size_t bind(const char *name, uint16_t priority);

  virtual int MPI_File_call_errhandler(MPI_File fh, int errorcode);

  virtual int MPI_File_create_errhandler(
      MPI_File_errhandler_function *file_errhandler_fn,
      MPI_Errhandler *errhandler);

  virtual int MPI_File_get_errhandler(MPI_File file,
                                      MPI_Errhandler *errhandler);

  virtual int MPI_File_set_errhandler(MPI_File file, MPI_Errhandler errhandler);

  virtual int MPI_File_open(MPI_Comm comm, const char *filename, int amode,
                            MPI_Info info, MPI_File *fh);

  virtual int MPI_File_close(MPI_File *fh);

  virtual int MPI_File_delete(const char *filename, MPI_Info info);

  virtual int MPI_File_set_size(MPI_File fh, MPI_Offset size);

  virtual int MPI_File_preallocate(MPI_File fh, MPI_Offset size);

  virtual int MPI_File_get_size(MPI_File fh, MPI_Offset *size);

  virtual int MPI_File_get_group(MPI_File fh, MPI_Group *group);

  virtual int MPI_File_get_amode(MPI_File fh, int *amode);

  virtual int MPI_File_set_info(MPI_File fh, MPI_Info info);

  virtual int MPI_File_get_info(MPI_File fh, MPI_Info *info_used);

  virtual int MPI_File_set_view(MPI_File fh, MPI_Offset disp,
                                MPI_Datatype etype, MPI_Datatype filetype,
                                const char *datarep, MPI_Info info);

  virtual int MPI_File_get_view(MPI_File fh, MPI_Offset *disp,
                                MPI_Datatype *etype, MPI_Datatype *filetype,
                                char *datarep);

  virtual int MPI_File_read_at(MPI_File fh, MPI_Offset offset, void *buf,
                               int count, MPI_Datatype datatype,
                               MPI_Status *status);

  virtual int MPI_File_read_at_all(MPI_File fh, MPI_Offset offset, void *buf,
                                   int count, MPI_Datatype datatype,
                                   MPI_Status *status);

  virtual int MPI_File_write_at(MPI_File fh, MPI_Offset offset, const void *buf,
                                int count, MPI_Datatype datatype,
                                MPI_Status *status);

  virtual int MPI_File_write_at_all(MPI_File fh, MPI_Offset offset,
                                    const void *buf, int count,
                                    MPI_Datatype datatype, MPI_Status *status);

  virtual int MPI_File_iread_at(MPI_File fh, MPI_Offset offset, void *buf,
                                int count, MPI_Datatype datatype,
                                MPI_Request *request);

  virtual int MPI_File_iwrite_at(MPI_File fh, MPI_Offset offset,
                                 const void *buf, int count,
                                 MPI_Datatype datatype, MPI_Request *request);

  virtual int MPI_File_read(MPI_File fh, void *buf, int count,
                            MPI_Datatype datatype, MPI_Status *status);

  virtual int MPI_File_read_all(MPI_File fh, void *buf, int count,
                                MPI_Datatype datatype, MPI_Status *status);

  virtual int MPI_File_write(MPI_File fh, const void *buf, int count,
                             MPI_Datatype datatype, MPI_Status *status);

  virtual int MPI_File_write_all(MPI_File fh, const void *buf, int count,
                                 MPI_Datatype datatype, MPI_Status *status);

  virtual int MPI_File_iread(MPI_File fh, void *buf, int count,
                             MPI_Datatype datatype, MPI_Request *request);

  virtual int MPI_File_iwrite(MPI_File fh, const void *buf, int count,
                              MPI_Datatype datatype, MPI_Request *request);

  virtual int MPI_File_seek(MPI_File fh, MPI_Offset offset, int whence);

  virtual int MPI_File_get_position(MPI_File fh, MPI_Offset *offset);

  virtual int MPI_File_get_byte_offset(MPI_File fh, MPI_Offset offset,
                                       MPI_Offset *disp);

  virtual int MPI_File_read_shared(MPI_File fh, void *buf, int count,
                                   MPI_Datatype datatype, MPI_Status *status);

  virtual int MPI_File_write_shared(MPI_File fh, const void *buf, int count,
                                    MPI_Datatype datatype, MPI_Status *status);

  virtual int MPI_File_iread_shared(MPI_File fh, void *buf, int count,
                                    MPI_Datatype datatype,
                                    MPI_Request *request);

  virtual int MPI_File_iwrite_shared(MPI_File fh, const void *buf, int count,
                                     MPI_Datatype datatype,
                                     MPI_Request *request);

  virtual int MPI_File_read_ordered(MPI_File fh, void *buf, int count,
                                    MPI_Datatype datatype, MPI_Status *status);

  virtual int MPI_File_write_ordered(MPI_File fh, const void *buf, int count,
                                     MPI_Datatype datatype, MPI_Status *status);

  virtual int MPI_File_seek_shared(MPI_File fh, MPI_Offset offset, int whence);

  virtual int MPI_File_get_position_shared(MPI_File fh, MPI_Offset *offset);

  virtual int MPI_File_read_at_all_begin(MPI_File fh, MPI_Offset offset,
                                         void *buf, int count,
                                         MPI_Datatype datatype);

  virtual int MPI_File_read_at_all_end(MPI_File fh, void *buf,
                                       MPI_Status *status);

  virtual int MPI_File_write_at_all_begin(MPI_File fh, MPI_Offset offset,
                                          const void *buf, int count,
                                          MPI_Datatype datatype);

  virtual int MPI_File_write_at_all_end(MPI_File fh, const void *buf,
                                        MPI_Status *status);

  virtual int MPI_File_read_all_begin(MPI_File fh, void *buf, int count,
                                      MPI_Datatype datatype);

  virtual int MPI_File_read_all_end(MPI_File fh, void *buf, MPI_Status *status);

  virtual int MPI_File_write_all_begin(MPI_File fh, const void *buf, int count,
                                       MPI_Datatype datatype);

  virtual int MPI_File_write_all_end(MPI_File fh, const void *buf,
                                     MPI_Status *status);

  virtual int MPI_File_read_ordered_begin(MPI_File fh, void *buf, int count,
                                          MPI_Datatype datatype);

  virtual int MPI_File_read_ordered_end(MPI_File fh, void *buf,
                                        MPI_Status *status);

  virtual int MPI_File_write_ordered_begin(MPI_File fh, const void *buf,
                                           int count, MPI_Datatype datatype);

  virtual int MPI_File_write_ordered_end(MPI_File fh, const void *buf,
                                         MPI_Status *status);

  virtual int MPI_File_get_type_extent(MPI_File fh, MPI_Datatype datatype,
                                       MPI_Aint *extent);

  virtual int MPI_File_set_atomicity(MPI_File fh, int flag);

  virtual int MPI_File_get_atomicity(MPI_File fh, int *flag);

  virtual int MPI_File_sync(MPI_File fh);

  virtual int MPI_File_iread_at_all(MPI_File fh, MPI_Offset offset, void *buf,
                                    int count, MPI_Datatype datatype,
                                    MPI_Request *request);

  virtual int MPI_File_iwrite_at_all(MPI_File fh, MPI_Offset offset,
                                     const void *buf, int count,
                                     MPI_Datatype datatype,
                                     MPI_Request *request);

  virtual int MPI_File_iread_all(MPI_File fh, void *buf, int count,
                                 MPI_Datatype datatype, MPI_Request *request);

  virtual int MPI_File_iwrite_all(MPI_File fh, const void *buf, int count,
                                  MPI_Datatype datatype, MPI_Request *request);

  virtual int MPI_File_read_c(MPI_File fh, void *buf, MPI_Count count,
                              MPI_Datatype datatype, MPI_Status *status);

  virtual int MPI_File_read_all_c(MPI_File fh, void *buf, MPI_Count count,
                                  MPI_Datatype datatype, MPI_Status *status);

  virtual int MPI_File_read_all_begin_c(MPI_File fh, void *buf, MPI_Count count,
                                        MPI_Datatype datatype);

  virtual int MPI_File_read_at_c(MPI_File fh, MPI_Offset offset, void *buf,
                                 MPI_Count count, MPI_Datatype datatype,
                                 MPI_Status *status);

  virtual int MPI_File_read_at_all_c(MPI_File fh, MPI_Offset offset, void *buf,
                                     MPI_Count count, MPI_Datatype datatype,
                                     MPI_Status *status);

  virtual int MPI_File_read_at_all_begin_c(MPI_File fh, MPI_Offset offset,
                                           void *buf, MPI_Count count,
                                           MPI_Datatype datatype);

  virtual int MPI_File_read_ordered_c(MPI_File fh, void *buf, MPI_Count count,
                                      MPI_Datatype datatype,
                                      MPI_Status *status);

  virtual int MPI_File_read_ordered_begin_c(MPI_File fh, void *buf,
                                            MPI_Count count,
                                            MPI_Datatype datatype);

  virtual int MPI_File_read_shared_c(MPI_File fh, void *buf, MPI_Count count,
                                     MPI_Datatype datatype, MPI_Status *status);

  virtual int MPI_File_write_c(MPI_File fh, const void *buf, MPI_Count count,
                               MPI_Datatype datatype, MPI_Status *status);

  virtual int MPI_File_write_all_c(MPI_File fh, const void *buf,
                                   MPI_Count count, MPI_Datatype datatype,
                                   MPI_Status *status);

  virtual int MPI_File_write_all_begin_c(MPI_File fh, const void *buf,
                                         MPI_Count count,
                                         MPI_Datatype datatype);

  virtual int MPI_File_write_at_c(MPI_File fh, MPI_Offset offset,
                                  const void *buf, MPI_Count count,
                                  MPI_Datatype datatype, MPI_Status *status);

  virtual int MPI_File_write_at_all_c(MPI_File fh, MPI_Offset offset,
                                      const void *buf, MPI_Count count,
                                      MPI_Datatype datatype,
                                      MPI_Status *status);

  virtual int MPI_File_write_at_all_begin_c(MPI_File fh, MPI_Offset offset,
                                            const void *buf, MPI_Count count,
                                            MPI_Datatype datatype);

  virtual int MPI_File_write_ordered_c(MPI_File fh, const void *buf,
                                       MPI_Count count, MPI_Datatype datatype,
                                       MPI_Status *status);

  virtual int MPI_File_write_ordered_begin_c(MPI_File fh, const void *buf,
                                             MPI_Count count,
                                             MPI_Datatype datatype);

  virtual int MPI_File_write_shared_c(MPI_File fh, const void *buf,
                                      MPI_Count count, MPI_Datatype datatype,
                                      MPI_Status *status);

  virtual int MPI_File_iread_c(MPI_File fh, void *buf, MPI_Count count,
                               MPI_Datatype datatype, MPI_Request *request);

  virtual int MPI_File_iread_all_c(MPI_File fh, void *buf, MPI_Count count,
                                   MPI_Datatype datatype, MPI_Request *request);

  virtual int MPI_File_iread_at_c(MPI_File fh, MPI_Offset offset, void *buf,
                                  MPI_Count count, MPI_Datatype datatype,
                                  MPI_Request *request);

  virtual int MPI_File_iread_at_all_c(MPI_File fh, MPI_Offset offset, void *buf,
                                      MPI_Count count, MPI_Datatype datatype,
                                      MPI_Request *request);

  virtual int MPI_File_iread_shared_c(MPI_File fh, void *buf, MPI_Count count,
                                      MPI_Datatype datatype,
                                      MPI_Request *request);

  virtual int MPI_File_iwrite_c(MPI_File fh, const void *buf, MPI_Count count,
                                MPI_Datatype datatype, MPI_Request *request);

  virtual int MPI_File_iwrite_all_c(MPI_File fh, const void *buf,
                                    MPI_Count count, MPI_Datatype datatype,
                                    MPI_Request *request);

  virtual int MPI_File_iwrite_at_c(MPI_File fh, MPI_Offset offset,
                                   const void *buf, MPI_Count count,
                                   MPI_Datatype datatype, MPI_Request *request);

  virtual int MPI_File_iwrite_at_all_c(MPI_File fh, MPI_Offset offset,
                                       const void *buf, MPI_Count count,
                                       MPI_Datatype datatype,
                                       MPI_Request *request);

  virtual int MPI_File_iwrite_shared_c(MPI_File fh, const void *buf,
                                       MPI_Count count, MPI_Datatype datatype,
                                       MPI_Request *request);

  virtual int MPI_File_get_type_extent_c(MPI_File fh, MPI_Datatype datatype,
                                         MPI_Count *extent);

  virtual MPI_File MPI_File_f2c(MPI_Fint file);

  virtual MPI_Fint MPI_File_c2f(MPI_File file);

  GOTCHA_MACRO_VAR(MPI_File_call_errhandler)

  GOTCHA_MACRO_VAR(MPI_File_create_errhandler)

  GOTCHA_MACRO_VAR(MPI_File_get_errhandler)

  GOTCHA_MACRO_VAR(MPI_File_set_errhandler)

  GOTCHA_MACRO_VAR(MPI_File_open)

  GOTCHA_MACRO_VAR(MPI_File_close)

  GOTCHA_MACRO_VAR(MPI_File_delete)

  GOTCHA_MACRO_VAR(MPI_File_set_size)

  GOTCHA_MACRO_VAR(MPI_File_preallocate)

  GOTCHA_MACRO_VAR(MPI_File_get_size)

  GOTCHA_MACRO_VAR(MPI_File_get_group)

  GOTCHA_MACRO_VAR(MPI_File_get_amode)

  GOTCHA_MACRO_VAR(MPI_File_set_info)

  GOTCHA_MACRO_VAR(MPI_File_get_info)

  GOTCHA_MACRO_VAR(MPI_File_set_view)

  GOTCHA_MACRO_VAR(MPI_File_get_view)

  GOTCHA_MACRO_VAR(MPI_File_read_at)

  GOTCHA_MACRO_VAR(MPI_File_read_at_all)

  GOTCHA_MACRO_VAR(MPI_File_write_at)

  GOTCHA_MACRO_VAR(MPI_File_write_at_all)

  GOTCHA_MACRO_VAR(MPI_File_iread_at)

  GOTCHA_MACRO_VAR(MPI_File_iwrite_at)

  GOTCHA_MACRO_VAR(MPI_File_read)

  GOTCHA_MACRO_VAR(MPI_File_read_all)

  GOTCHA_MACRO_VAR(MPI_File_write)

  GOTCHA_MACRO_VAR(MPI_File_write_all)

  GOTCHA_MACRO_VAR(MPI_File_iread)

  GOTCHA_MACRO_VAR(MPI_File_iwrite)

  GOTCHA_MACRO_VAR(MPI_File_seek)

  GOTCHA_MACRO_VAR(MPI_File_get_position)

  GOTCHA_MACRO_VAR(MPI_File_get_byte_offset)

  GOTCHA_MACRO_VAR(MPI_File_read_shared)

  GOTCHA_MACRO_VAR(MPI_File_write_shared)

  GOTCHA_MACRO_VAR(MPI_File_iread_shared)

  GOTCHA_MACRO_VAR(MPI_File_iwrite_shared)

  GOTCHA_MACRO_VAR(MPI_File_read_ordered)

  GOTCHA_MACRO_VAR(MPI_File_write_ordered)

  GOTCHA_MACRO_VAR(MPI_File_seek_shared)

  GOTCHA_MACRO_VAR(MPI_File_get_position_shared)

  GOTCHA_MACRO_VAR(MPI_File_read_at_all_begin)

  GOTCHA_MACRO_VAR(MPI_File_read_at_all_end)

  GOTCHA_MACRO_VAR(MPI_File_write_at_all_begin)

  GOTCHA_MACRO_VAR(MPI_File_write_at_all_end)

  GOTCHA_MACRO_VAR(MPI_File_read_all_begin)

  GOTCHA_MACRO_VAR(MPI_File_read_all_end)

  GOTCHA_MACRO_VAR(MPI_File_write_all_begin)

  GOTCHA_MACRO_VAR(MPI_File_write_all_end)

  GOTCHA_MACRO_VAR(MPI_File_read_ordered_begin)

  GOTCHA_MACRO_VAR(MPI_File_read_ordered_end)

  GOTCHA_MACRO_VAR(MPI_File_write_ordered_begin)

  GOTCHA_MACRO_VAR(MPI_File_write_ordered_end)

  GOTCHA_MACRO_VAR(MPI_File_get_type_extent)

  GOTCHA_MACRO_VAR(MPI_File_set_atomicity)

  GOTCHA_MACRO_VAR(MPI_File_get_atomicity)

  GOTCHA_MACRO_VAR(MPI_File_sync)

  GOTCHA_MACRO_VAR(MPI_File_iread_at_all)

  GOTCHA_MACRO_VAR(MPI_File_iwrite_at_all)

  GOTCHA_MACRO_VAR(MPI_File_iread_all)

  GOTCHA_MACRO_VAR(MPI_File_iwrite_all)

  GOTCHA_MACRO_VAR(MPI_File_read_c)

  GOTCHA_MACRO_VAR(MPI_File_read_all_c)

  GOTCHA_MACRO_VAR(MPI_File_read_all_begin_c)

  GOTCHA_MACRO_VAR(MPI_File_read_at_c)

  GOTCHA_MACRO_VAR(MPI_File_read_at_all_c)

  GOTCHA_MACRO_VAR(MPI_File_read_at_all_begin_c)

  GOTCHA_MACRO_VAR(MPI_File_read_ordered_c)

  GOTCHA_MACRO_VAR(MPI_File_read_ordered_begin_c)

  GOTCHA_MACRO_VAR(MPI_File_read_shared_c)

  GOTCHA_MACRO_VAR(MPI_File_write_c)

  GOTCHA_MACRO_VAR(MPI_File_write_all_c)

  GOTCHA_MACRO_VAR(MPI_File_write_all_begin_c)

  GOTCHA_MACRO_VAR(MPI_File_write_at_c)

  GOTCHA_MACRO_VAR(MPI_File_write_at_all_c)

  GOTCHA_MACRO_VAR(MPI_File_write_at_all_begin_c)

  GOTCHA_MACRO_VAR(MPI_File_write_ordered_c)

  GOTCHA_MACRO_VAR(MPI_File_write_ordered_begin_c)

  GOTCHA_MACRO_VAR(MPI_File_write_shared_c)

  GOTCHA_MACRO_VAR(MPI_File_iread_c)

  GOTCHA_MACRO_VAR(MPI_File_iread_all_c)

  GOTCHA_MACRO_VAR(MPI_File_iread_at_c)

  GOTCHA_MACRO_VAR(MPI_File_iread_at_all_c)

  GOTCHA_MACRO_VAR(MPI_File_iread_shared_c)

  GOTCHA_MACRO_VAR(MPI_File_iwrite_c)

  GOTCHA_MACRO_VAR(MPI_File_iwrite_all_c)

  GOTCHA_MACRO_VAR(MPI_File_iwrite_at_c)

  GOTCHA_MACRO_VAR(MPI_File_iwrite_at_all_c)

  GOTCHA_MACRO_VAR(MPI_File_iwrite_shared_c)

  GOTCHA_MACRO_VAR(MPI_File_get_type_extent_c)

  GOTCHA_MACRO_VAR(MPI_File_f2c)

  GOTCHA_MACRO_VAR(MPI_File_c2f)
};
}  // namespace brahma

GOTCHA_MACRO_TYPEDEF(MPI_File_call_errhandler, int,
                     (MPI_File fh, int errorcode), (fh, errorcode),
                     brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_create_errhandler, int,
                     (MPI_File_errhandler_function * file_errhandler_fn,
                      MPI_Errhandler *errhandler),
                     (file_errhandler_fn, errhandler), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_get_errhandler, int,
                     (MPI_File file, MPI_Errhandler *errhandler),
                     (file, errhandler), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_set_errhandler, int,
                     (MPI_File file, MPI_Errhandler errhandler),
                     (file, errhandler), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_open, int,
                     (MPI_Comm comm, const char *filename, int amode,
                      MPI_Info info, MPI_File *fh),
                     (comm, filename, amode, info, fh), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_close, int, (MPI_File * fh), (fh), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_delete, int,
                     (const char *filename, MPI_Info info), (filename, info),
                     brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_set_size, int, (MPI_File fh, MPI_Offset size),
                     (fh, size), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_preallocate, int, (MPI_File fh, MPI_Offset size),
                     (fh, size), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_get_size, int, (MPI_File fh, MPI_Offset *size),
                     (fh, size), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_get_group, int, (MPI_File fh, MPI_Group *group),
                     (fh, group), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_get_amode, int, (MPI_File fh, int *amode),
                     (fh, amode), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_set_info, int, (MPI_File fh, MPI_Info info),
                     (fh, info), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_get_info, int, (MPI_File fh, MPI_Info *info_used),
                     (fh, info_used), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_set_view, int,
                     (MPI_File fh, MPI_Offset disp, MPI_Datatype etype,
                      MPI_Datatype filetype, const char *datarep,
                      MPI_Info info),
                     (fh, disp, etype, filetype, datarep, info), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_get_view, int,
                     (MPI_File fh, MPI_Offset *disp, MPI_Datatype *etype,
                      MPI_Datatype *filetype, char *datarep),
                     (fh, disp, etype, filetype, datarep), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_at, int,
                     (MPI_File fh, MPI_Offset offset, void *buf, int count,
                      MPI_Datatype datatype, MPI_Status *status),
                     (fh, offset, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_at_all, int,
                     (MPI_File fh, MPI_Offset offset, void *buf, int count,
                      MPI_Datatype datatype, MPI_Status *status),
                     (fh, offset, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_at, int,
                     (MPI_File fh, MPI_Offset offset, const void *buf,
                      int count, MPI_Datatype datatype, MPI_Status *status),
                     (fh, offset, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_at_all, int,
                     (MPI_File fh, MPI_Offset offset, const void *buf,
                      int count, MPI_Datatype datatype, MPI_Status *status),
                     (fh, offset, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iread_at, int,
                     (MPI_File fh, MPI_Offset offset, void *buf, int count,
                      MPI_Datatype datatype, MPI_Request *request),
                     (fh, offset, buf, count, datatype, request),
                     brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iwrite_at, int,
                     (MPI_File fh, MPI_Offset offset, const void *buf,
                      int count, MPI_Datatype datatype, MPI_Request *request),
                     (fh, offset, buf, count, datatype, request),
                     brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read, int,
                     (MPI_File fh, void *buf, int count, MPI_Datatype datatype,
                      MPI_Status *status),
                     (fh, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_all, int,
                     (MPI_File fh, void *buf, int count, MPI_Datatype datatype,
                      MPI_Status *status),
                     (fh, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write, int,
                     (MPI_File fh, const void *buf, int count,
                      MPI_Datatype datatype, MPI_Status *status),
                     (fh, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_all, int,
                     (MPI_File fh, const void *buf, int count,
                      MPI_Datatype datatype, MPI_Status *status),
                     (fh, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iread, int,
                     (MPI_File fh, void *buf, int count, MPI_Datatype datatype,
                      MPI_Request *request),
                     (fh, buf, count, datatype, request), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iwrite, int,
                     (MPI_File fh, const void *buf, int count,
                      MPI_Datatype datatype, MPI_Request *request),
                     (fh, buf, count, datatype, request), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_seek, int,
                     (MPI_File fh, MPI_Offset offset, int whence),
                     (fh, offset, whence), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_get_position, int,
                     (MPI_File fh, MPI_Offset *offset), (fh, offset),
                     brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_get_byte_offset, int,
                     (MPI_File fh, MPI_Offset offset, MPI_Offset *disp),
                     (fh, offset, disp), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_shared, int,
                     (MPI_File fh, void *buf, int count, MPI_Datatype datatype,
                      MPI_Status *status),
                     (fh, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_shared, int,
                     (MPI_File fh, const void *buf, int count,
                      MPI_Datatype datatype, MPI_Status *status),
                     (fh, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iread_shared, int,
                     (MPI_File fh, void *buf, int count, MPI_Datatype datatype,
                      MPI_Request *request),
                     (fh, buf, count, datatype, request), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iwrite_shared, int,
                     (MPI_File fh, const void *buf, int count,
                      MPI_Datatype datatype, MPI_Request *request),
                     (fh, buf, count, datatype, request), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_ordered, int,
                     (MPI_File fh, void *buf, int count, MPI_Datatype datatype,
                      MPI_Status *status),
                     (fh, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_ordered, int,
                     (MPI_File fh, const void *buf, int count,
                      MPI_Datatype datatype, MPI_Status *status),
                     (fh, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_seek_shared, int,
                     (MPI_File fh, MPI_Offset offset, int whence),
                     (fh, offset, whence), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_get_position_shared, int,
                     (MPI_File fh, MPI_Offset *offset), (fh, offset),
                     brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_at_all_begin, int,
                     (MPI_File fh, MPI_Offset offset, void *buf, int count,
                      MPI_Datatype datatype),
                     (fh, offset, buf, count, datatype), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_at_all_end, int,
                     (MPI_File fh, void *buf, MPI_Status *status),
                     (fh, buf, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_at_all_begin, int,
                     (MPI_File fh, MPI_Offset offset, const void *buf,
                      int count, MPI_Datatype datatype),
                     (fh, offset, buf, count, datatype), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_at_all_end, int,
                     (MPI_File fh, const void *buf, MPI_Status *status),
                     (fh, buf, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_all_begin, int,
                     (MPI_File fh, void *buf, int count, MPI_Datatype datatype),
                     (fh, buf, count, datatype), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_all_end, int,
                     (MPI_File fh, void *buf, MPI_Status *status),
                     (fh, buf, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_all_begin, int,
                     (MPI_File fh, const void *buf, int count,
                      MPI_Datatype datatype),
                     (fh, buf, count, datatype), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_all_end, int,
                     (MPI_File fh, const void *buf, MPI_Status *status),
                     (fh, buf, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_ordered_begin, int,
                     (MPI_File fh, void *buf, int count, MPI_Datatype datatype),
                     (fh, buf, count, datatype), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_ordered_end, int,
                     (MPI_File fh, void *buf, MPI_Status *status),
                     (fh, buf, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_ordered_begin, int,
                     (MPI_File fh, const void *buf, int count,
                      MPI_Datatype datatype),
                     (fh, buf, count, datatype), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_ordered_end, int,
                     (MPI_File fh, const void *buf, MPI_Status *status),
                     (fh, buf, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_get_type_extent, int,
                     (MPI_File fh, MPI_Datatype datatype, MPI_Aint *extent),
                     (fh, datatype, extent), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_set_atomicity, int, (MPI_File fh, int flag),
                     (fh, flag), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_get_atomicity, int, (MPI_File fh, int *flag),
                     (fh, flag), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_sync, int, (MPI_File fh), (fh), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iread_at_all, int,
                     (MPI_File fh, MPI_Offset offset, void *buf, int count,
                      MPI_Datatype datatype, MPI_Request *request),
                     (fh, offset, buf, count, datatype, request),
                     brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iwrite_at_all, int,
                     (MPI_File fh, MPI_Offset offset, const void *buf,
                      int count, MPI_Datatype datatype, MPI_Request *request),
                     (fh, offset, buf, count, datatype, request),
                     brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iread_all, int,
                     (MPI_File fh, void *buf, int count, MPI_Datatype datatype,
                      MPI_Request *request),
                     (fh, buf, count, datatype, request), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iwrite_all, int,
                     (MPI_File fh, const void *buf, int count,
                      MPI_Datatype datatype, MPI_Request *request),
                     (fh, buf, count, datatype, request), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_c, int,
                     (MPI_File fh, void *buf, MPI_Count count,
                      MPI_Datatype datatype, MPI_Status *status),
                     (fh, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_all_c, int,
                     (MPI_File fh, void *buf, MPI_Count count,
                      MPI_Datatype datatype, MPI_Status *status),
                     (fh, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_all_begin_c, int,
                     (MPI_File fh, void *buf, MPI_Count count,
                      MPI_Datatype datatype),
                     (fh, buf, count, datatype), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_at_c, int,
                     (MPI_File fh, MPI_Offset offset, void *buf,
                      MPI_Count count, MPI_Datatype datatype,
                      MPI_Status *status),
                     (fh, offset, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_at_all_c, int,
                     (MPI_File fh, MPI_Offset offset, void *buf,
                      MPI_Count count, MPI_Datatype datatype,
                      MPI_Status *status),
                     (fh, offset, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_at_all_begin_c, int,
                     (MPI_File fh, MPI_Offset offset, void *buf,
                      MPI_Count count, MPI_Datatype datatype),
                     (fh, offset, buf, count, datatype), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_ordered_c, int,
                     (MPI_File fh, void *buf, MPI_Count count,
                      MPI_Datatype datatype, MPI_Status *status),
                     (fh, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_ordered_begin_c, int,
                     (MPI_File fh, void *buf, MPI_Count count,
                      MPI_Datatype datatype),
                     (fh, buf, count, datatype), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_read_shared_c, int,
                     (MPI_File fh, void *buf, MPI_Count count,
                      MPI_Datatype datatype, MPI_Status *status),
                     (fh, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_c, int,
                     (MPI_File fh, const void *buf, MPI_Count count,
                      MPI_Datatype datatype, MPI_Status *status),
                     (fh, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_all_c, int,
                     (MPI_File fh, const void *buf, MPI_Count count,
                      MPI_Datatype datatype, MPI_Status *status),
                     (fh, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_all_begin_c, int,
                     (MPI_File fh, const void *buf, MPI_Count count,
                      MPI_Datatype datatype),
                     (fh, buf, count, datatype), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_at_c, int,
                     (MPI_File fh, MPI_Offset offset, const void *buf,
                      MPI_Count count, MPI_Datatype datatype,
                      MPI_Status *status),
                     (fh, offset, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_at_all_c, int,
                     (MPI_File fh, MPI_Offset offset, const void *buf,
                      MPI_Count count, MPI_Datatype datatype,
                      MPI_Status *status),
                     (fh, offset, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_at_all_begin_c, int,
                     (MPI_File fh, MPI_Offset offset, const void *buf,
                      MPI_Count count, MPI_Datatype datatype),
                     (fh, offset, buf, count, datatype), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_ordered_c, int,
                     (MPI_File fh, const void *buf, MPI_Count count,
                      MPI_Datatype datatype, MPI_Status *status),
                     (fh, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_ordered_begin_c, int,
                     (MPI_File fh, const void *buf, MPI_Count count,
                      MPI_Datatype datatype),
                     (fh, buf, count, datatype), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_write_shared_c, int,
                     (MPI_File fh, const void *buf, MPI_Count count,
                      MPI_Datatype datatype, MPI_Status *status),
                     (fh, buf, count, datatype, status), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iread_c, int,
                     (MPI_File fh, void *buf, MPI_Count count,
                      MPI_Datatype datatype, MPI_Request *request),
                     (fh, buf, count, datatype, request), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iread_all_c, int,
                     (MPI_File fh, void *buf, MPI_Count count,
                      MPI_Datatype datatype, MPI_Request *request),
                     (fh, buf, count, datatype, request), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iread_at_c, int,
                     (MPI_File fh, MPI_Offset offset, void *buf,
                      MPI_Count count, MPI_Datatype datatype,
                      MPI_Request *request),
                     (fh, offset, buf, count, datatype, request),
                     brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iread_at_all_c, int,
                     (MPI_File fh, MPI_Offset offset, void *buf,
                      MPI_Count count, MPI_Datatype datatype,
                      MPI_Request *request),
                     (fh, offset, buf, count, datatype, request),
                     brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iread_shared_c, int,
                     (MPI_File fh, void *buf, MPI_Count count,
                      MPI_Datatype datatype, MPI_Request *request),
                     (fh, buf, count, datatype, request), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iwrite_c, int,
                     (MPI_File fh, const void *buf, MPI_Count count,
                      MPI_Datatype datatype, MPI_Request *request),
                     (fh, buf, count, datatype, request), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iwrite_all_c, int,
                     (MPI_File fh, const void *buf, MPI_Count count,
                      MPI_Datatype datatype, MPI_Request *request),
                     (fh, buf, count, datatype, request), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iwrite_at_c, int,
                     (MPI_File fh, MPI_Offset offset, const void *buf,
                      MPI_Count count, MPI_Datatype datatype,
                      MPI_Request *request),
                     (fh, offset, buf, count, datatype, request),
                     brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iwrite_at_all_c, int,
                     (MPI_File fh, MPI_Offset offset, const void *buf,
                      MPI_Count count, MPI_Datatype datatype,
                      MPI_Request *request),
                     (fh, offset, buf, count, datatype, request),
                     brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_iwrite_shared_c, int,
                     (MPI_File fh, const void *buf, MPI_Count count,
                      MPI_Datatype datatype, MPI_Request *request),
                     (fh, buf, count, datatype, request), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_get_type_extent_c, int,
                     (MPI_File fh, MPI_Datatype datatype, MPI_Count *extent),
                     (fh, datatype, extent), brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_f2c, MPI_File, (MPI_Fint file), (file),
                     brahma::MPIIO);

GOTCHA_MACRO_TYPEDEF(MPI_File_c2f, MPI_Fint, (MPI_File file), (file),
                     brahma::MPIIO);

template <typename C>
size_t brahma::MPIIO::bind(const char *name, uint16_t priority) {
  GOTCHA_BINDING_MACRO(MPI_File_call_errhandler, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_create_errhandler, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_get_errhandler, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_set_errhandler, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_open, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_close, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_delete, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_set_size, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_preallocate, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_get_size, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_get_group, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_get_amode, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_set_info, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_get_info, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_set_view, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_get_view, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_at, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_at_all, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_at, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_at_all, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iread_at, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iwrite_at, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_all, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_all, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iread, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iwrite, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_seek, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_get_position, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_get_byte_offset, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_shared, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_shared, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iread_shared, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iwrite_shared, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_ordered, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_ordered, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_seek_shared, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_get_position_shared, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_at_all_begin, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_at_all_end, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_at_all_begin, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_at_all_end, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_all_begin, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_all_end, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_all_begin, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_all_end, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_ordered_begin, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_ordered_end, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_ordered_begin, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_ordered_end, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_get_type_extent, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_set_atomicity, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_get_atomicity, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_sync, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iread_at_all, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iwrite_at_all, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iread_all, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iwrite_all, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_all_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_all_begin_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_at_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_at_all_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_at_all_begin_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_ordered_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_ordered_begin_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_read_shared_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_all_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_all_begin_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_at_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_at_all_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_at_all_begin_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_ordered_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_ordered_begin_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_write_shared_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iread_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iread_all_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iread_at_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iread_at_all_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iread_shared_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iwrite_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iwrite_all_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iwrite_at_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iwrite_at_all_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_iwrite_shared_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_get_type_extent_c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_f2c, brahma::MPIIO);

  GOTCHA_BINDING_MACRO(MPI_File_c2f, brahma::MPIIO);

  num_bindings = bindings.size();
  if (num_bindings > 0) {
    char tool_name[64];
    sprintf(tool_name, "%s_mpiio", name);
    gotcha_binding_t *raw_bindings = bindings.data();
    gotcha_wrap(raw_bindings, num_bindings, tool_name);
    gotcha_set_priority(tool_name, priority);
  }
  return num_bindings;
}

#endif  // BRAHMA_ENABLE_MPI
#endif  // BRAHMA_MPIIO_H
