# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.22)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS gotcha brahma)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target gotcha
add_library(gotcha SHARED IMPORTED)

set_target_properties(gotcha PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/workspace/haridev/dftracer-project/brahma/build_verify/_deps/gotcha-src/include;/usr/workspace/haridev/dftracer-project/brahma/build_verify/_deps/gotcha-build/include;/usr/workspace/haridev/dftracer-project/brahma/build_verify/_deps/gotcha-src/include"
)

# Create imported target brahma
add_library(brahma SHARED IMPORTED)

set_target_properties(brahma PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BRAHMA_HAS_CONFIG;BRAHMA_MPI_IMPL_CRAYMPICH"
  INTERFACE_LINK_LIBRARIES "MPI::MPI_C;gotcha;HDF5::HDF5"
)

# Import target "gotcha" for configuration "Debug"
set_property(TARGET gotcha APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gotcha PROPERTIES
  IMPORTED_LOCATION_DEBUG "/usr/workspace/haridev/dftracer-project/brahma/build_verify/lib64/libgotcha.so.2.4.4"
  IMPORTED_SONAME_DEBUG "libgotcha.so.2"
  )

# Import target "brahma" for configuration "Debug"
set_property(TARGET brahma APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(brahma PROPERTIES
  IMPORTED_LOCATION_DEBUG "/usr/workspace/haridev/dftracer-project/brahma/build_verify/lib64/libbrahma.so.4.1.2"
  IMPORTED_SONAME_DEBUG "libbrahma.so.1"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
