-- LMod module file for BRAHMA

-- CMAKE_INSTALL_PREFIX: /usr/local
-- CMAKE_BUILD_TYPE: Debug
-- C Compiler: /opt/cray/pe/craype/2.7.35/bin/cc
-- C FLAGS:  -fPIC -Wall -Wextra -pedantic -Wno-unused-parameter -Wno-deprecated-declarations -fsanitize=address -fno-omit-frame-pointer -fsanitize-recover=address
-- C FLAGS_DEBUG: -g
-- C FLAGS_RELWITHDEBINFO: -O2 -g -DNDEBUG
-- C FLAGS_RELEASE: -O3 -DNDEBUG
-- CXX Compiler: /opt/cray/pe/craype/2.7.35/bin/CC
-- CXX FLAGS:  -fPIC -Wall -Wextra -pedantic -Wno-unused-parameter -Wnon-virtual-dtor -Wno-deprecated-declarations -fsanitize=address -fno-omit-frame-pointer -fsanitize-recover=address
-- CXX FLAGS_DEBUG: -g
-- CXX FLAGS_RELWITHDEBINFO: -O2 -g -DNDEBUG
-- CXX FLAGS_RELEASE: -O3 -DNDEBUG
-- BRAHMA_GNU_LINUX: TRUE
-- BRAHMA_HAS_DOXYGEN: 
-- BRAHMA_HAS_STD_FILESYSTEM: TRUE
-- BRAHMA_HAS_STD_FSTREAM_FD: TRUE

help(
[[
Brahma (BRAHMA) version (1, 0, 10).
]])

whatis("Package: BRAHMA")
whatis("Version: (1, 0, 10)")
whatis("Description: DYnamic and Asynchronous Data streamliner (BRAHMA).")
whatis("URL: https://github.com/flux-framework/brahma")
whatis("CMAKE_INSTALL_PREFIX: /usr/local")
whatis("CMAKE_BUILD_TYPE: Debug")
whatis("C Compiler: /opt/cray/pe/craype/2.7.35/bin/cc")
whatis("C FLAGS:  -fPIC -Wall -Wextra -pedantic -Wno-unused-parameter -Wno-deprecated-declarations -fsanitize=address -fno-omit-frame-pointer -fsanitize-recover=address")
whatis("C FLAGS_DEBUG: -g")
whatis("C FLAGS_RELWITHDEBINFO: -O2 -g -DNDEBUG")
whatis("C FLAGS_RELEASE: -O3 -DNDEBUG")
whatis("CXX Compiler: /opt/cray/pe/craype/2.7.35/bin/CC")
whatis("CXX FLAGS:  -fPIC -Wall -Wextra -pedantic -Wno-unused-parameter -Wnon-virtual-dtor -Wno-deprecated-declarations -fsanitize=address -fno-omit-frame-pointer -fsanitize-recover=address")
whatis("CXX FLAGS_DEBUG: -g")
whatis("CXX FLAGS_RELWITHDEBINFO: -O2 -g -DNDEBUG")
whatis("CXX FLAGS_RELEASE: -O3 -DNDEBUG")
whatis("BRAHMA_GNU_LINUX: TRUE")
whatis("BRAHMA_HAS_DOXYGEN: ")
whatis("BRAHMA_HAS_STD_FILESYSTEM: TRUE")
whatis("BRAHMA_HAS_STD_FSTREAM_FD: TRUE")

prepend_path("PATH","/usr/local/bin")
prepend_path("LD_LIBRARY_PATH","/usr/local/lib64")

pushenv("BRAHMA_DIR","/usr/local/lib64/cmake/brahma")
